version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./migrations/init-database.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
